import React, { useState } from 'react';
import { Link } from 'react-router-dom';
// Bootstrap 5.3.8 is loaded for the homepage ONLY: the import below resolves to
// the scoped stylesheet generated by scripts/lib/bootstrap-homepage-css.js,
// so no other route is restyled.
import '../../generated/homepage-bootstrap.css';
import 'animate.css/animate.min.css';
import './home-landing.css';
import Strings from '../../data/strings.js';
import LegalFooter from '../legal/LegalFooter.jsx';
import ConversationCarousel from './ConversationCarousel.jsx';
import { HOME_LANGUAGES } from '../../data/languages.js';
import headerLogo from '../../assets/img/uff-logo.png';
import teacherPhoto from '../../assets/img/teacherprofile.webp';

// The teacher is a proper noun, so its name is a module constant, not a
// strings.js key (the hi/bn script guard would fail on a Latin-only entry).
const TEACHER_NAME = 'Joe Walsh';

const HOW_IT_WORKS_KEYS = [
    'home_landing_how_1',
    'home_landing_how_2',
    'home_landing_how_3',
    'home_landing_how_4',
    'home_landing_how_5',
];

// Public homepage: the friend-challenge entry plus short marketing sections.
// Built with Bootstrap 5.3.8 (navbar, grid, cards, list-group, buttons) in the
// main app's palette. The hero's only job is to accept a friend's share code (or
// send the visitor into the Would You Rather ask lesson); the container owns
// lookup + error + the language-change handler.
export default function HomeLanding({
    lang = 'en',
    isLoggedIn = false,
    error = null,
    loading = false,
    onSubmitCode,
    onNoCode,
    onInputChange,
    onLanguageChange,
    showcaseVideos = [],
}) {
    const [code, setCode] = useState('');

    const languageCode = String(lang).toUpperCase();
    const selectedLanguage = HOME_LANGUAGES.some((l) => l.value === languageCode) ? languageCode : 'EN';

    function handleSubmit(e) {
        e.preventDefault();
        onSubmitCode?.(code);
    }

    function handleChange(e) {
        setCode(e.target.value);
        onInputChange?.();
    }

    return (
        <div className="uff-home-bs">
            <nav className="navbar uff-navbar sticky-top" data-testid="landing-topbar">
                <div className="container">
                    <Link className="navbar-brand" to="/">
                        <img
                            src={headerLogo}
                            alt={Strings.get('home_title', lang)}
                            data-testid="home-logo"
                        />
                    </Link>
                    <div className="d-flex align-items-center gap-2">
                        <label className="visually-hidden" htmlFor="landingLanguageSelect">
                            {Strings.get('home_landing_language_label', lang)}
                        </label>
                        <select
                            id="landingLanguageSelect"
                            data-testid="landing-language-select"
                            className="form-select form-select-sm w-auto"
                            aria-label={Strings.get('home_landing_language_label', lang)}
                            value={selectedLanguage}
                            onChange={(e) => onLanguageChange?.(e.target.value)}
                        >
                            {HOME_LANGUAGES.map((l) => (
                                <option key={l.value} value={l.value}>{l.label}</option>
                            ))}
                        </select>
                        <Link
                            to={isLoggedIn ? '/home' : '/login'}
                            data-testid="landing-account-link"
                            className="btn btn-sm btn-uff-topbar"
                        >
                            {isLoggedIn ? Strings.get('home_home', lang) : Strings.get('sign_in', lang)}
                        </Link>
                    </div>
                </div>
            </nav>

            <header className="uff-hero uff-section animate__animated animate__fadeIn">
                <div className="container">
                    <div className="row justify-content-center text-center">
                        <div className="col-12 col-lg-8 col-xl-7">
                            <h1 className="uff-hero-title text-white mb-3" data-testid="share-code-headline">
                                {Strings.get('home_landing_headline', lang)}
                            </h1>

                            <div className="card border-secondary text-start mt-4" data-testid="share-code-card">
                                <div className="card-body">
                                    <h2 className="h5 fw-bold text-white mb-3" data-testid="share-code-subheadline">
                                        {Strings.get('home_landing_subheadline', lang)}
                                    </h2>

                                    <form onSubmit={handleSubmit}>
                                        <label className="visually-hidden" htmlFor="shareCodeInput">
                                            {Strings.get('home_landing_code_placeholder', lang)}
                                        </label>
                                        <input
                                            id="shareCodeInput"
                                            data-testid="share-code-input"
                                            type="text"
                                            value={code}
                                            onChange={handleChange}
                                            placeholder={Strings.get('home_landing_code_placeholder', lang)}
                                            autoCapitalize="none"
                                            autoCorrect="off"
                                            spellCheck={false}
                                            className="form-control form-control-lg"
                                        />
                                        {error !== null && (
                                            <div
                                                data-testid="share-code-error"
                                                role="alert"
                                                className="alert mt-2 mb-0 py-2"
                                            >
                                                {error}
                                            </div>
                                        )}
                                        <button type="submit" data-testid="share-code-go" disabled={loading}
                                                className="btn btn-uff-primary btn-lg w-100 mt-3">
                                            {Strings.get('home_landing_go', lang)}
                                        </button>
                                    </form>
                                    <div className="mt-2">
                                        <button type="button" data-testid="no-code" onClick={onNoCode}
                                                className="btn btn-uff-outline w-100">
                                            {Strings.get('home_landing_no_code', lang)}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <section className="uff-section" id="how-it-works" data-testid="how-it-works">
                <div className="container">
                    <div className="row g-4 align-items-start">
                        <div className="col-12 col-lg-5">
                            <h2 className="uff-section-title text-white" data-testid="how-it-works-heading">
                                {Strings.get('home_landing_how_heading', lang)}
                            </h2>
                        </div>
                        <div className="col-12 col-lg-7">
                            <ul className="list-group" data-testid="how-it-works-list">
                                {HOW_IT_WORKS_KEYS.map((key, i) => (
                                    <li key={key} data-testid={`how-it-works-item-${i + 1}`}
                                        className="list-group-item d-flex align-items-start gap-3 animate__animated animate__fadeInUp"
                                        style={{ animationDelay: `${i * 90}ms` }}>
                                        <i className="bi bi-check-circle-fill uff-check" aria-hidden="true"></i>
                                        <span>{Strings.get(key, lang)}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </div>
                </div>
            </section>

            <ConversationCarousel lang={lang} videos={showcaseVideos} />

            <section className="uff-section uff-section--alt" id="about" data-testid="about-teacher">
                <div className="container">
                    <div className="row g-4 align-items-center">
                        <div className="col-12 col-lg-3 text-center text-lg-start">
                            <img
                                data-testid="about-teacher-photo"
                                src={teacherPhoto}
                                alt={TEACHER_NAME}
                                className="uff-teacher-photo uff-teacher-photo--lg mx-auto mx-lg-0"
                            />
                        </div>
                        <div className="col-12 col-lg-9">
                            <h2 className="uff-section-title text-white" data-testid="about-teacher-heading">
                                {Strings.get('home_landing_about_heading', lang)}
                            </h2>
                            <p className="h5 fw-semibold mb-2" data-testid="about-teacher-name">{TEACHER_NAME}</p>
                            <p className="lead text-secondary mb-0" data-testid="about-teacher-credentials">
                                {Strings.get('home_landing_about_credentials', lang)}
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            <div className="uff-footer py-4 mt-auto">
                <LegalFooter lang={lang} />
            </div>
        </div>
    );
}
